### ISSUE TITLE
Make multiple solutions for puzzles possible

### ISSUE THREAD

**Issue by 14422** [kiigame/adventure_engine#22]
Currently there is no possibility to have multiple solutions for one puzzle. Refactoring both javascript and JSON is required.

Ideally puzzles should have multiple possible logical solutions.

**Comment by evktalo** [comment]
This should be possible thanks to 9e5cd95 but untested. Lots of opportunities to break your adventure!

**Comment by evktalo** [comment]
This is definitely possible since the changes mentioned in the above comment.
