### ISSUE TITLE
Create an editor to ease creation of adventures

### ISSUE THREAD

**Issue by eetumans** [kiigame/adventure_engine#27]
Some kind of editor would be nice to ease the creation of adventures and to minimize the need to manually edit JSON files.

Something like creating and editing objects, graphically placing them to their desired locations (with the relative locations as mentioned in #7), managing interactions, etc.

**Comment by evktalo** [comment]
The above editor is abandoned.

It might be good if the editor functionality was accessible while playing the game; or to put it another way, the game was immediately playable in the editor.
